name: Trigger Netify Build Hook
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install
        run: npm ci
      - name: run headless tests
        run: npm run ci

  deploy:
    name: Request Host Webhook
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.NETIFY_GIT_MAIN_HOOK}}