name: Trigger Netlify Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.ANGULAR_CI_CD}}
